export const INITIALIZE_DATA_REQUEST = 'INITIALIZE_DATA_REQUEST';
export const INITIALIZE_DATA_SUCCESS = 'INITIALIZE_DATA_SUCCESS';
export const INITIALIZE_DATA_FAILURE = 'INITIALIZE_DATA_FAILURE';

export const GET_ACTIVE_NOTE_REQUEST = 'GET_ACTIVE_NOTE_REQUEST';
export const GET_ACTIVE_NOTE_SUCCESS = 'GET_ACTIVE_NOTE_SUCCESS';
export const GET_ACTIVE_NOTE_FAILURE = 'GET_ACTIVE_NOTE_FAILURE';

export const EDIT_TEXT_ACTIVE_NOTE_REQUEST = 'EDIT_TEXT_ACTIVE_NOTE_REQUEST';
export const EDIT_TEXT_ACTIVE_NOTE_SUCCESS = 'EDIT_TEXT_ACTIVE_NOTE_SUCCESS';
export const EDIT_TEXT_ACTIVE_NOTE_FAILURE = 'EDIT_TEXT_ACTIVE_NOTE_FAILURE';

export const DATE_EDIT_ACTIVE_NOTE_REQUEST = 'DATE_EDIT_ACTIVE_NOTE_REQUEST';
export const DATE_EDIT_ACTIVE_NOTE_SUCCESS = 'DATE_EDIT_ACTIVE_NOTE_SUCCESS';
export const DATE_EDIT_ACTIVE_NOTE_FAILURE = 'DATE_EDIT_ACTIVE_NOTE_FAILURE';

export const DELETE_ACTIVE_NOTE_REQUEST = 'DELETE_ACTIVE_NOTE_REQUEST';
export const DELETE_ACTIVE_NOTE_SUCCESS = 'DELETE_ACTIVE_NOTE_SUCCESS';
export const DELETE_ACTIVE_NOTE_FAILURE = 'DELETE_ACTIVE_NOTE_FAILURE';

export const SET_RESIZE_BORDER_WIDTH = 'SET_RESIZE_BORDER_WIDTH';
