export enum ActionTypes {
  INITIALIZE_DATA_REQUEST = 'INITIALIZE_DATA_REQUEST',
  INITIALIZE_DATA_SUCCESS = 'INITIALIZE_DATA_SUCCESS',
  INITIALIZE_DATA_FAILURE = 'INITIALIZE_DATA_FAILURE',
  
  GET_ACTIVE_NOTE_REQUEST = 'GET_ACTIVE_NOTE_REQUEST',
  GET_ACTIVE_NOTE_SUCCESS = 'GET_ACTIVE_NOTE_SUCCESS',
  GET_ACTIVE_NOTE_FAILURE = 'GET_ACTIVE_NOTE_FAILURE',
  
  EDIT_TEXT_ACTIVE_NOTE_REQUEST = 'EDIT_TEXT_ACTIVE_NOTE_REQUEST',
  EDIT_TEXT_ACTIVE_NOTE_SUCCESS = 'EDIT_TEXT_ACTIVE_NOTE_SUCCESS',
  EDIT_TEXT_ACTIVE_NOTE_FAILURE = 'EDIT_TEXT_ACTIVE_NOTE_FAILURE',
  
  DATE_EDIT_ACTIVE_NOTE_REQUEST = 'DATE_EDIT_ACTIVE_NOTE_REQUEST',
  DATE_EDIT_ACTIVE_NOTE_SUCCESS = 'DATE_EDIT_ACTIVE_NOTE_SUCCESS',
  DATE_EDIT_ACTIVE_NOTE_FAILURE = 'DATE_EDIT_ACTIVE_NOTE_FAILURE',
  
  DELETE_ACTIVE_NOTE_REQUEST = 'DELETE_ACTIVE_NOTE_REQUEST',
  DELETE_ACTIVE_NOTE_SUCCESS = 'DELETE_ACTIVE_NOTE_SUCCESS',
  DELETE_ACTIVE_NOTE_FAILURE = 'DELETE_ACTIVE_NOTE_FAILURE',
  
  CREATE_ACTIVE_NOTE_REQUEST = 'CREATE_ACTIVE_NOTE_REQUEST',
  CREATE_ACTIVE_NOTE_SUCCESS = 'CREATE_ACTIVE_NOTE_SUCCESS',
  CREATE_ACTIVE_NOTE_FAILURE = 'CREATE_ACTIVE_NOTE_FAILURE',
  
  SET_RESIZE_BORDER_WIDTH = 'SET_RESIZE_BORDER_WIDTH',

  SET_FILTER_TEXT_REQUEST = 'SET_FILTER_TEXT_REQUEST',
  SET_FILTER_TEXT_SUCCESS = 'SET_FILTER_TEXT_SUCCESS',
  SET_FILTER_TEXT_FAILURE = 'SET_FILTER_TEXT_FAILURE',

  SET_SEARCH_FOCUS = 'SET_SEARCH_FOCUS',
};
